import Head from "next/head";
import Layout from "../components/Layout.jsx";
import Hero from '../components/Hero.jsx';
import css from '../styles/Home.module.css';
import Services from "../components/Services.jsx";
import { client } from "../lib/client.js";
import Menu from "../components/Menu.jsx";

export default function Home(props) {
  // console.log(props.pizzas);
  return (
        <Layout>
          <div className={css.container}>
            <Head>
              <title>Salasa</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/Logo.png" />
            </Head>
            {/* body */}
            <main>
              <Hero/>
              <Services/>
              <Menu pizzas={props.pizzas}/>
            </main>
          </div>
        </Layout>
  )
};

export const getServerSideProps = async () => {
  const query = '*[_type == "pizza"]';
  const pizzas = await client.fetch(query);
  return {
    props: {
      pizzas
    }
  }
}
